### ISSUE TITLE
cannot connect to Sybase ASE 15.0.3

### ISSUE THREAD

**Issue by javabilities** [thda/tds#2]
This project looks very promising. Thanks for working on it and sharing. 

I'm trying to use this project to connect to a Sybase ASE 15.0.3 database. I have build the connection string as per the instructions. The sql.Open() command works with no error, but when I try db.Ping() or db.Query() I get an exception. I'm new to Go and am having a hard time finding helpful information from the error message. I am using the latest from master. Do you have any pointers? The error is below. Thanks,

panic: runtime error: index out of range

goroutine 1 [running]:
github.com/thda/tds.(*session).login(0xc00055c340, 0xc00040c756, 0x23, 0xc00040c746, 0x6, 0xc00040c74d, 0x8, 0x0, 0x0, 0x0, ...)
        /Users/user/Development/Go/src/github.com/thda/tds/session.go:226 +0x1bd6
github.com/thda/tds.newSession(0xc00040c756, 0x23, 0xc00040c746, 0x6, 0xc00040c74d, 0x8, 0x0, 0x0, 0x0, 0x0, ...)
        /Users/user/Development/Go/src/github.com/thda/tds/session.go:124 +0x5fa
github.com/thda/tds.NewConn(0xc00040c740, 0x3d, 0x15477d8, 0xc0004a11c8, 0x10421e4)
        /Users/user/Development/Go/src/github.com/thda/tds/driver.go:145 +0x124
github.com/thda/tds.(*sybDriver).Open(0x1ebb1e0, 0xc00040c740, 0x3d, 0xc0004a11d8, 0x10352c3, 0x10c6ddd, 0xc0004a11e8)
        /Users/user/Development/Go/src/github.com/thda/tds/driver.go:177 +0x39

**Comment by thda** [comment]
Hi, and thanks for reporting.
I think I've fixed it.
Could you please rebuild from master and retry ?
Also, can you please let me know the value of the parameter "net password encryption required" just for reference ?

Thanks

**Comment by javabilities** [comment]
I've pulled the latest and get a clearer error message: Login failed. I'm using the correct credentials, so it must be in my connection settings.

prm.encryptPassword is never assigned in driver.go. I created a minor pull request for you to review.
With this change and providing the explicit query parameter ?encryptPassword=no I was able to connect to the database.

The default value of the parameter encryptPassword=try does not work in my case, I'm not sure why. I have to explicitly set it to no.

**Comment by thda** [comment]
Indeed it looks like 15.0.3's password encryption is not the same as 15.7, and uses no nonce.
I'll have to get my hand on a 15.0.3 and try myself.

For my reference, are you using any special character in the password ?
Could you please give me the output of "select @@version" ?

In the meantime I've merged your pull request.
Will work on password encryption for this version.

If you can run the test suite on your server it would be of great help.

Thanks again

**Comment by javabilities** [comment]
The password is alphanumeric, no special characters.

I looked at the tests and I have limited permissions on this database so I can't run the tests, sorry.

Thanks for the help!

**Comment by thda** [comment]
I've updated master so that you don't have to set the encryptPassword parameter.
Updated the readme to mention that the driver does not support ASE < 15.5 password encryption.

**Comment by javabilities** [comment]
That's awesome. The project is very useful. Thanks for working on it. I don't normally work with Sybase but if I find a way to contribute more I will.
